const API=(window.PAYX_CONFIG?.API_BASE||"").replace(/\/$/,""),$=s=>document.querySelector(s),key="payx_admin_session";const token=()=>localStorage.getItem(key);async function api(p,o={}){const r=await fetch(API+p,{...o,headers:{"Content-Type":"application/json",Authorization:`Bearer ${token()}`,...o.headers}});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.error||`HTTP ${r.status}`);return d}function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}function note(s,b=false){$("#notice").textContent=s;$("#notice").className=b?"notice error":"notice"}function show(v){document.querySelectorAll("[data-admin-view]").forEach(x=>x.hidden=x.dataset.adminView!==v);document.querySelectorAll("[data-admin-nav]").forEach(x=>x.classList.toggle("active",x.dataset.adminNav===v));$("#pageTitle").textContent=v[0].toUpperCase()+v.slice(1)}
async function dash(){let d=await api("/api/v1/admin/dashboard");$("#metrics").innerHTML=[["Total users",d.users],["Payment volume",`₹${d.volume}`],["Today volume",`₹${d.today}`],["Month volume",`₹${d.month}`],["Payment links",d.links],["Transactions",d.transactions]].map(x=>`<article class="stat"><span>${x[0]}</span><strong>${x[1]}</strong></article>`).join("");$("#adminRecent").innerHTML=(d.recent||[]).map(x=>`<tr><td>${esc(x.id)}</td><td>${esc(x.email||"")}</td><td>₹${x.amount}</td><td>${esc(x.status)}</td></tr>`).join("")}
async function users(){let d=await api("/api/v1/admin/users");$("#usersTable").innerHTML=(d.users||[]).map(x=>`<tr><td>${esc(x.full_name)}</td><td>${esc(x.email)}</td><td>${esc(x.role)}</td><td>${esc(x.status)}</td><td><button class="small" data-user="${x.id}" data-status="${x.status==="active"?"suspended":"active"}">${x.status==="active"?"Suspend":"Activate"}</button></td></tr>`).join("");document.querySelectorAll("[data-user]").forEach(b=>b.onclick=async()=>{try{await api(`/api/v1/admin/users/${b.dataset.user}`,{method:"PATCH",body:JSON.stringify({status:b.dataset.status})});await users()}catch(e){note(e.message,true)}})}
async function tx(){let d=await api("/api/v1/admin/transactions");$("#adminTx").innerHTML=(d.transactions||[]).map(x=>`<tr><td>${esc(x.id)}</td><td>${esc(x.email||"")}</td><td>₹${x.amount}</td><td>${esc(x.status)}</td></tr>`).join("")}
async function plans(){let d=await api("/api/v1/admin/plans");$("#planTable").innerHTML=(d.plans||[]).map(p=>`<tr><td>${esc(p.name)}</td><td>₹${p.price}</td><td>${p.validity_days} days</td><td>${p.link_limit}</td><td>${p.active?"Active":"Inactive"}</td></tr>`).join("")}
$("#adminLogin").onsubmit=async e=>{e.preventDefault();try{let d=await api("/api/v1/auth/login",{method:"POST",body:JSON.stringify({identity:$("#adminIdentity").value,password:$("#adminPassword").value})});localStorage.setItem(key,d.token);await boot()}catch(e){note(e.message,true)}};
document.querySelectorAll("[data-admin-nav]").forEach(b=>b.onclick=async()=>{let v=b.dataset.adminNav;show(v);try{if(v==="dashboard")await dash();if(v==="users")await users();if(v==="transactions")await tx();if(v==="plans")await plans()}catch(e){note(e.message,true)}});
$("#planForm").onsubmit=async e=>{e.preventDefault();try{await api("/api/v1/admin/plans",{method:"POST",body:JSON.stringify({name:$("#planName").value,price:Number($("#planPrice").value),validityDays:Number($("#planDays").value),linkLimit:Number($("#planLimit").value),apiAccess:$("#planApi").checked})});note("Plan created.");await plans()}catch(e){note(e.message,true)}};
$("#adminLogout").onclick=()=>{localStorage.removeItem(key);location.reload()};
async function boot(){try{let d=await api("/api/v1/me");if(d.user.role!=="admin")throw Error("Admin access required.");$("#adminAuth").hidden=true;$("#adminApp").hidden=false;await dash()}catch(e){localStorage.removeItem(key);$("#adminAuth").hidden=false;$("#adminApp").hidden=true;note(e.message,true)}}if(token())boot();
