const API=(window.PAYX_CONFIG?.API_BASE||"").replace(/\/$/,""),$=s=>document.querySelector(s),tokenKey="payx_session";const token=()=>localStorage.getItem(tokenKey);let mode="login";
const money=n=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"}).format(Number(n)||0);
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
function msg(t,bad=false){$("#notice").textContent=t;$("#notice").className=bad?"notice error":"notice"}
async function api(path,opts={}){const headers={"Content-Type":"application/json",...(opts.headers||{})};if(token())headers.Authorization=`Bearer ${token()}`;const r=await fetch(API+path,{...opts,headers});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.error||`Request failed (${r.status})`);return d}
function view(v){document.querySelectorAll("[data-view]").forEach(e=>e.hidden=e.dataset.view!==v);document.querySelectorAll("[data-nav]").forEach(e=>e.classList.toggle("active",e.dataset.nav===v));const names={dashboard:"Dashboard",links:"Payment Links",transactions:"Transactions",developer:"Developer",subscriptions:"Subscriptions",settings:"Settings",profile:"Profile"};$("#pageTitle").textContent=names[v]||"PayX"}
async function loadDashboard(){const d=await api("/api/v1/dashboard");$("#statVolume").textContent=money(d.totalVolume);$("#statSuccess").textContent=d.successful;$("#statLinks").textContent=d.linkCount;$("#statPending").textContent=d.pending;$("#recent").innerHTML=(d.recent||[]).map(x=>`<tr><td>${esc(x.id)}</td><td>${money(x.amount)}</td><td><span class="pill">${esc(x.status)}</span></td><td>${new Date(x.created_at).toLocaleString()}</td></tr>`).join("")||'<tr><td colspan="4">No transactions yet</td></tr>'}
async function loadLinks(){const d=await api("/api/v1/payment-links");$("#linksTable").innerHTML=(d.links||[]).map(x=>`<tr><td>${esc(x.title)}</td><td>${money(x.amount)}</td><td>${esc(x.status)}</td><td><button class="small" data-copy="${esc(x.url)}">Copy link</button></td></tr>`).join("")||'<tr><td colspan="4">No links created</td></tr>';document.querySelectorAll("[data-copy]").forEach(b=>b.onclick=()=>navigator.clipboard.writeText(b.dataset.copy).then(()=>msg("Link copied.")))}
async function loadTransactions(){const d=await api("/api/v1/transactions");$("#transactionsTable").innerHTML=(d.transactions||[]).map(x=>`<tr><td>${esc(x.id)}</td><td>${money(x.amount)}</td><td>${esc(x.status)}</td><td>${new Date(x.created_at).toLocaleString()}</td></tr>`).join("")||'<tr><td colspan="4">No transactions yet</td></tr>'}
async function loadPlans(){const d=await api("/api/v1/subscriptions/plans");$("#plans").innerHTML=(d.plans||[]).map(p=>`<article class="plan"><h3>${esc(p.name)}</h3><div class="price">${money(p.price)} <small>/ ${esc(p.validity_label)}</small></div><p>${p.link_limit} payment links</p><p>${p.api_access?"API access":"Dashboard access"}</p><button data-plan="${esc(p.id)}">Subscribe</button></article>`).join("")||"<p>No plans configured yet.</p>";document.querySelectorAll("[data-plan]").forEach(b=>b.onclick=async()=>{try{const d=await api("/api/v1/subscriptions/subscribe",{method:"POST",body:JSON.stringify({planId:b.dataset.plan})});location.href=`payment.html?link=${encodeURIComponent(d.link.slug)}`}catch(e){msg(e.message,true)}})}
async function profile(){const d=await api("/api/v1/me");$("#userLabel").textContent=d.user.full_name;$("#profileName").value=d.user.full_name||"";$("#profileEmail").value=d.user.email||"";$("#profileMobile").value=d.user.mobile||"";$("#businessName").value=d.user.business_name||"";$("#checkoutNote").value=d.user.checkout_note||"";$("#supportEmail").value=d.user.support_email||""}
function docs(){$("#docs").textContent=`PayX API\nBase URL: ${API}\nAuth: Authorization: Bearer <merchant_api_key>\n\nPOST /api/v1/payment-links\n{ "amount": 499, "title": "Order payment", "expiryMinutes": 10 }\n\nGET /api/v1/transactions\nGET /api/v1/payments/:id\n\nUse server-side requests for secret API keys. Verify payment status from PayX API; never trust redirects or client callbacks.`}
async function enter(){document.querySelector('[data-view="auth"]').hidden=true;$("#logoutBtn").hidden=false;try{await profile();view("dashboard");await loadDashboard();docs()}catch(e){localStorage.removeItem(tokenKey);authView();msg(e.message,true)}}
function authView(){document.querySelectorAll("[data-view]").forEach(e=>e.hidden=e.dataset.view!=="auth");$("#logoutBtn").hidden=true}
document.querySelectorAll("[data-nav]").forEach(b=>b.onclick=async()=>{const v=b.dataset.nav;view(v);try{if(v==="dashboard")await loadDashboard();if(v==="links")await loadLinks();if(v==="transactions")await loadTransactions();if(v==="subscriptions")await loadPlans();if(v==="developer")docs();if(v==="profile"||v==="settings")await profile()}catch(e){msg(e.message,true)}});
document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>document.querySelector(`[data-nav="${b.dataset.go}"]`).click());
$("#loginTab").onclick=()=>setMode("login");$("#registerTab").onclick=()=>setMode("register");
function setMode(m){mode=m;$("#loginTab").classList.toggle("selected",m==="login");$("#registerTab").classList.toggle("selected",m==="register");$("#nameWrap").hidden=m!=="register";$("#fullName").required=m==="register";$("#authSubmit").textContent=m==="login"?"Login":"Create account";$("#authTitle").textContent=m==="login"?"Welcome to PayX":"Create your account"}
$("#authForm").onsubmit=async e=>{e.preventDefault();try{const body={identity:$("#identity").value.trim(),password:$("#password").value};if(mode==="register"){body.fullName=$("#fullName").value.trim();const d=await api("/api/v1/auth/register",{method:"POST",body:JSON.stringify(body)});msg("Account created. Please log in.");setMode("login")}else{const d=await api("/api/v1/auth/login",{method:"POST",body:JSON.stringify(body)});localStorage.setItem(tokenKey,d.token);await enter()}}catch(err){msg(err.message,true)}};
$("#linkForm").onsubmit=async e=>{e.preventDefault();try{const amount=Number(String($("#linkAmount").value).replace(/[^0-9.]/g,""));if(!Number.isFinite(amount)||amount<1)throw Error("Enter a valid amount of at least ₹1.");const d=await api("/api/v1/payment-links",{method:"POST",body:JSON.stringify({amount,title:$("#linkTitle").value.trim(),description:$("#linkDescription").value.trim(),expiryMinutes:Number($("#linkExpiry").value)})});msg("Payment link created.");await loadLinks();const url=d.link.url;await navigator.clipboard?.writeText(url);msg("Payment link created and copied: "+url)}catch(err){msg(err.message,true)}};
$("#createKey").onclick=async()=>{try{const d=await api("/api/v1/api-keys",{method:"POST",body:"{}"});$("#newKey").textContent=d.key;msg("API key created. Copy and store it securely now.")}catch(e){msg(e.message,true)}};
$("#profileForm").onsubmit=async e=>{e.preventDefault();try{await api("/api/v1/profile",{method:"PATCH",body:JSON.stringify({fullName:$("#profileName").value,mobile:$("#profileMobile").value})});msg("Profile updated.")}catch(e){msg(e.message,true)}};
$("#settingsForm").onsubmit=async e=>{e.preventDefault();try{await api("/api/v1/settings",{method:"PATCH",body:JSON.stringify({businessName:$("#businessName").value,checkoutNote:$("#checkoutNote").value,supportEmail:$("#supportEmail").value})});msg("Settings saved.")}catch(e){msg(e.message,true)}};
$("#logoutBtn").onclick=()=>{localStorage.removeItem(tokenKey);authView();msg("Logged out.")};
if(token())enter();else authView();
