const API=(window.PAYX_CONFIG?.API_BASE||"").replace(/\/$/,"");const q=new URLSearchParams(location.search);const slug=q.get("link");let orderId=null,loop=null,done=false;
const $=s=>document.querySelector(s);const money=n=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"}).format(Number(n)||0);
async function req(path,opts={}){const r=await fetch(API+path,{...opts,headers:{"Content-Type":"application/json",...(opts.headers||{})}});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);return d}
function status(t){$("#status").textContent=t}
async function init(){if(!slug){status("Payment link is missing.");return}try{const d=await req(`/api/v1/public/links/${encodeURIComponent(slug)}`);$("#amount").textContent=money(d.link.amount);$("#title").textContent=d.link.title;$("#payBtn").hidden=false;$("#payBtn").onclick=createOrder; if(d.link.status!=="active"){status("This payment link is no longer active.");$("#payBtn").hidden=true}}catch(e){status(e.message)}}
async function createOrder(){ $("#payBtn").disabled=true;status("Creating secure payment order…");try{const d=await req(`/api/v1/public/links/${encodeURIComponent(slug)}/pay`,{method:"POST",body:"{}"});orderId=d.order.id;$("#upiId").textContent=d.order.upiId||"UPI details unavailable";$("#upiWrap").hidden=!d.order.upiId;$("#checkBtn").hidden=false;$("#checkBtn").onclick=()=>poll(true);status("Order created. Complete payment in your UPI app, then wait for verification.");poll(false)}catch(e){status(errorMessage(e));$("#payBtn").disabled=false;$("#payBtn").hidden=false}}
function errorMessage(e){const s=e.message||"Request failed";if(/401|invalid api key|missing x-famapi/i.test(s))return "Payment provider authentication failed. Please contact support.";if(/400|positive number|validation/i.test(s))return "Payment amount is invalid. Please contact the merchant.";if(/403|limit reached/i.test(s))return "Payment service limit reached. Please try later.";if(/429|too many/i.test(s))return "Please wait a moment. Verification is rate limited.";return "Network issue. Retrying payment verification…"}
async function poll(manual){if(!orderId||done)return;try{const d=await req(`/api/v1/public/payments/${encodeURIComponent(orderId)}?link=${encodeURIComponent(slug)}`);const s=d.order.status;status(({success:"Payment verified successfully.",failed:"Payment failed.",expired:"Payment expired.",refunded:"Payment refunded.",pending:"Payment is pending. Complete payment in your UPI app."})[s]||"Checking payment status…");if(["success","failed","expired","refunded"].includes(s)){done=true;if(loop)clearTimeout(loop);$("#payBtn").hidden=true;return}}catch(e){status(errorMessage(e));}
if(!done)loop=setTimeout(()=>poll(false),manual?2500:4000)}
$("#copyUpi").onclick=()=>navigator.clipboard?.writeText($("#upiId").textContent).then(()=>status("UPI ID copied."));
init();
