import { createClient } from "@supabase/supabase-js";
import bcrypt from "bcryptjs";
import jwt from "jsonwebtoken";
import crypto from "node:crypto";

const db=()=>createClient(process.env.SUPABASE_URL,process.env.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false}});
const json=(res,status,data)=>{res.statusCode=status;res.setHeader("Content-Type","application/json; charset=utf-8");res.end(JSON.stringify(data));};
const fail=(status,error)=>Object.assign(new Error(error),{status});
const getBody=async req=>{if(req.body&&typeof req.body==="object")return req.body;let s="";for await(const c of req)s+=c;try{return s?JSON.parse(s):{}}catch{throw fail(400,"Invalid JSON body.")}};
const cleanAmount=v=>Number(String(v??"").replace(/[^0-9.]/g,""));
const sha=s=>crypto.createHash("sha256").update(s).digest("hex");
const id=()=>crypto.randomUUID();
const now=()=>new Date().toISOString();
const allowedOrigins=()=>String(process.env.FRONTEND_ORIGIN||"").split(",").map(x=>x.trim()).filter(Boolean);
function cors(req,res){const origin=req.headers.origin;const allow=allowedOrigins();if(origin&&allow.includes(origin)){res.setHeader("Access-Control-Allow-Origin",origin);res.setHeader("Vary","Origin");}res.setHeader("Access-Control-Allow-Headers","Content-Type, Authorization, X-PayX-Key");res.setHeader("Access-Control-Allow-Methods","GET, POST, PATCH, OPTIONS");res.setHeader("Access-Control-Max-Age","86400");}
function sign(user){return jwt.sign({sub:user.id,role:user.role},process.env.JWT_SECRET,{expiresIn:"12h",issuer:"PayX"});}
async function auth(req,admin=false){const h=req.headers.authorization||"";const token=h.startsWith("Bearer ")?h.slice(7):"";if(!token)throw fail(401,"Authentication required.");let p;try{p=jwt.verify(token,process.env.JWT_SECRET,{issuer:"PayX"})}catch{throw fail(401,"Session expired. Please log in again.")}const {data:user,error}=await db().from("users").select("*").eq("id",p.sub).maybeSingle();if(error||!user||user.status!=="active")throw fail(401,"Account unavailable.");if(admin&&user.role!=="admin")throw fail(403,"Admin access required.");return user;}
async function merchantKey(req){const k=req.headers["x-payx-key"]||(req.headers.authorization||"").replace(/^Bearer /,"");if(!k)throw fail(401,"PayX API key required.");const {data,error}=await db().from("api_keys").select("id,user_id,revoked_at").eq("key_hash",sha(k)).maybeSingle();if(error||!data||data.revoked_at)throw fail(401,"Invalid PayX API key.");await db().from("api_keys").update({last_used_at:now()}).eq("id",data.id);const {data:user}=await db().from("users").select("*").eq("id",data.user_id).maybeSingle();if(!user||user.status!=="active")throw fail(403,"Merchant account is inactive.");return user;}
async function currentUser(req){try{return await auth(req)}catch(e){if(e.status!==401)throw e;return await merchantKey(req)}}
async function fam(path,method="GET",body){if(!process.env.FAMAPI_KEY)throw fail(503,"FamApi is not configured.");let r;try{r=await fetch(`${process.env.FAMAPI_BASE_URL||"https://famapi-orcin.vercel.app"}${path}`,{method,headers:{"X-FamApi-Key":process.env.FAMAPI_KEY,"Content-Type":"application/json"},...(body?{body:JSON.stringify(body)}:{ }),signal:AbortSignal.timeout(15000)});}catch{throw fail(502,"FamApi network failure. Please retry.");}let d={};try{d=await r.json()}catch{}if(!r.ok){const m=d.error||d.message||`FamApi returned ${r.status}`;if(r.status===401)throw fail(502,"FamApi authentication failed; administrator must rotate/check the server key.");if(r.status===400)throw fail(400,m);if(r.status===403)throw fail(503,"FamApi monthly order limit reached or access denied.");if(r.status===404)throw fail(404,"FamApi order not found.");if(r.status===429)throw fail(429,"FamApi rate limit reached; retry with backoff.");throw fail(502,"FamApi temporary error.");}return d;}
async function audit(userId,action,detail={}){await db().from("audit_logs").insert({user_id:userId,action,detail});}
async function ownLink(user,slug){const {data,error}=await db().from("payment_links").select("*").eq("slug",slug).eq("user_id",user.id).maybeSingle();if(error||!data)throw fail(404,"Payment link not found.");return data;}
async function makeLink(user,b,options={}){const amount=cleanAmount(b.amount);if(!Number.isFinite(amount)||amount<1||amount>10000000)throw fail(400,"amount must be a positive number between ₹1 and ₹10,000,000.");const title=String(b.title||"Payment").trim().slice(0,100);if(!title)throw fail(400,"Payment link title is required.");const expiry=Math.max(1,Math.min(Number(b.expiryMinutes)||Number(process.env.DEFAULT_LINK_EXPIRY_MINUTES)||10,10080));const {data:sub}=await db().from("subscriptions").select("*,plans(link_limit,validity_days)").eq("user_id",user.id).eq("status","active").gt("expires_at",now()).order("expires_at",{ascending:false}).limit(1).maybeSingle();if(!sub&&!options.subscriptionPlanId)throw fail(403,"An active subscription is required to create payment links.");if(sub&&!options.subscriptionPlanId){const {count}=await db().from("payment_links").select("id",{count:"exact",head:true}).eq("user_id",user.id).gte("created_at",sub.starts_at);if((count||0)>=(sub.plans?.link_limit||0))throw fail(403,"Subscription payment-link limit reached.");}const slug=crypto.randomBytes(12).toString("hex");const base=process.env.PUBLIC_SITE_URL||"https://payxoffical.infinityfreeapp.com";const row={id:id(),user_id:user.id,slug,title,description:String(b.description||"").slice(0,500),amount,currency:"INR",status:"active",expires_at:new Date(Date.now()+expiry*60000).toISOString(),platform_fee_percent:Number(process.env.PLATFORM_FEE_PERCENT||2),metadata:options.subscriptionPlanId?{subscription_plan_id:options.subscriptionPlanId}:{},created_at:now()};const {data,error}=await db().from("payment_links").insert(row).select("*").single();if(error)throw fail(500,"Could not create payment link.");return {id:data.id,slug,url:`${base}/payment.html?link=${slug}`,title:data.title,amount:data.amount,status:data.status,expires_at:data.expires_at};}
async function startPayment(link){if(link.status!=="active"||new Date(link.expires_at).getTime()<Date.now())throw fail(410,"Payment link has expired.");const {data:existing}=await db().from("payment_orders").select("*").eq("link_id",link.id).eq("status","pending").gt("created_at",new Date(Date.now()-30*60000).toISOString()).order("created_at",{ascending:false}).limit(1).maybeSingle();if(existing)return {id:existing.provider_order_id,status:existing.status,upiId:existing.upi_id,amount:existing.amount};const amount=cleanAmount(link.amount);const ref=`PX-${link.id.slice(0,8)}-${Date.now()}`;const result=await fam("/api/v1/orders","POST",{amount,reference:ref,currency:"INR"});const o=result.order;if(!o?.id)throw fail(502,"FamApi did not return an order ID.");const fee=Number((amount*Number(link.platform_fee_percent||2)/100).toFixed(2));const {error}=await db().from("payment_orders").insert({id:id(),link_id:link.id,user_id:link.user_id,provider_order_id:String(o.id),amount,status:o.status||"pending",upi_id:o.upiId||null,platform_fee:fee,created_at:now()});if(error)throw fail(500,"Order was created by provider but could not be saved; contact support with reference "+ref);return {id:String(o.id),status:o.status||"pending",upiId:o.upiId||null,amount};}
async function verifyOrder(providerId,linkId){const {data:record,error}=await db().from("payment_orders").select("*,payment_links!inner(id,slug,user_id)").eq("provider_order_id",providerId).eq("link_id",linkId).maybeSingle();if(error||!record)throw fail(404,"Order not found.");if(["success","failed","expired","refunded"].includes(record.status))return record;const d=await fam(`/api/v1/orders/${encodeURIComponent(providerId)}`);const o=d.order;if(!o)throw fail(502,"FamApi returned an invalid order.");const status=["pending","success","failed","expired","refunded"].includes(o.status)?o.status:"pending";const patch={status,checked_at:now(),upi_id:o.upiId||record.upi_id};if(status==="success")patch.paid_at=record.paid_at||now();const {data,error:upErr}=await db().from("payment_orders").update(patch).eq("id",record.id).select("*").single();if(upErr)throw fail(500,"Could not update payment status.");if(status==="success"&&record.status!=="success"){await audit(record.user_id,"payment_verified",{order_id:providerId,amount:record.amount});const {data:link}=await db().from("payment_links").select("metadata").eq("id",record.link_id).maybeSingle();const planId=link?.metadata?.subscription_plan_id;if(planId){const {data:plan}=await db().from("plans").select("*").eq("id",planId).maybeSingle();if(plan){const {data:active}=await db().from("subscriptions").select("id").eq("user_id",record.user_id).eq("plan_id",planId).eq("status","active").gt("expires_at",now()).maybeSingle();if(!active){await db().from("subscriptions").update({status:"expired"}).eq("user_id",record.user_id).eq("status","active");await db().from("subscriptions").insert({user_id:record.user_id,plan_id:plan.id,status:"active",starts_at:now(),expires_at:new Date(Date.now()+plan.validity_days*86400000).toISOString()});}}}}return data;}
async function handler(req,res){cors(req,res);if(req.method==="OPTIONS"){res.statusCode=204;return res.end();}const url=new URL(req.url,"http://localhost");const p=url.pathname.replace(/\/+$/,"")||"/";const method=req.method;try{const b=await getBody(req);
if(method==="GET"&&p==="/api/health")return json(res,200,{success:true,service:"PayX API",time:now()});
if(method==="POST"&&p==="/api/v1/auth/register"){const identity=String(b.identity||"").trim().toLowerCase(),email=identity.includes("@")?identity:null,mobile=email?null:identity;const name=String(b.fullName||"").trim();if(!name||!identity||String(b.password||"").length<8)throw fail(400,"Name, email/mobile and password (8+ characters) are required.");if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw fail(400,"Invalid email address.");if(mobile&&!/^\+?[0-9]{8,15}$/.test(mobile))throw fail(400,"Enter a valid mobile number.");const row={id:id(),email,mobile,full_name:name,password_hash:await bcrypt.hash(String(b.password),12),role:"merchant",status:"active",created_at:now()};const {data,error}=await db().from("users").insert(row).select("id").single();if(error)throw fail(409,"Account already exists or could not be created.");return json(res,201,{success:true,userId:data.id,message:"Account created. Please log in."});}
if(method==="POST"&&p==="/api/v1/auth/login"){const ident=String(b.identity||"").trim().toLowerCase();if(!ident||!b.password)throw fail(400,"Identity and password are required.");const col=ident.includes("@")?"email":"mobile";const {data:u}=await db().from("users").select("*").eq(col,ident).maybeSingle();if(!u||!(await bcrypt.compare(String(b.password),u.password_hash)))throw fail(401,"Invalid login credentials.");if(u.status!=="active")throw fail(403,"Account is not active.");return json(res,200,{success:true,token:sign(u),user:{id:u.id,full_name:u.full_name,email:u.email,role:u.role}});}
if(method==="GET"&&p==="/api/v1/me"){const u=await auth(req);return json(res,200,{user:{id:u.id,email:u.email,mobile:u.mobile,full_name:u.full_name,role:u.role,business_name:u.business_name,checkout_note:u.checkout_note,support_email:u.support_email}});}
if(method==="PATCH"&&p==="/api/v1/profile"){const u=await auth(req);const patch={full_name:String(b.fullName||u.full_name).slice(0,100),mobile:b.mobile?String(b.mobile).slice(0,20):u.mobile};const {error}=await db().from("users").update(patch).eq("id",u.id);if(error)throw fail(500,"Profile update failed.");return json(res,200,{success:true});}
if(method==="PATCH"&&p==="/api/v1/settings"){const u=await auth(req);const patch={business_name:String(b.businessName||"").slice(0,120),checkout_note:String(b.checkoutNote||"").slice(0,160),support_email:String(b.supportEmail||"").slice(0,160)};const {error}=await db().from("users").update(patch).eq("id",u.id);if(error)throw fail(500,"Settings update failed.");return json(res,200,{success:true});}
if(method==="GET"&&p==="/api/v1/dashboard"){const u=await currentUser(req);const {data:links}=await db().from("payment_links").select("id").eq("user_id",u.id);const {data:orders}=await db().from("payment_orders").select("id,provider_order_id,amount,status,created_at").eq("user_id",u.id).order("created_at",{ascending:false}).limit(10);const all=orders||[];const {data:success}=await db().from("payment_orders").select("amount").eq("user_id",u.id).eq("status","success");return json(res,200,{totalVolume:(success||[]).reduce((s,x)=>s+Number(x.amount),0),successful:(success||[]).length,linkCount:(links||[]).length,pending:all.filter(x=>x.status==="pending").length,recent:all});}
if(method==="POST"&&p==="/api/v1/payment-links"){const u=await currentUser(req);const link=await makeLink(u,b);return json(res,201,{success:true,link});}
if(method==="GET"&&p==="/api/v1/payment-links"){const u=await currentUser(req);const {data,error}=await db().from("payment_links").select("*").eq("user_id",u.id).order("created_at",{ascending:false}).limit(100);if(error)throw fail(500,"Could not load links.");const base=process.env.PUBLIC_SITE_URL||"https://payxoffical.infinityfreeapp.com";return json(res,200,{links:(data||[]).map(x=>({...x,url:`${base}/payment.html?link=${x.slug}`}))});}
if(method==="GET"&&p.startsWith("/api/v1/public/links/")){const slug=decodeURIComponent(p.split("/").pop());const {data:l}=await db().from("payment_links").select("id,slug,title,description,amount,status,expires_at,user_id").eq("slug",slug).maybeSingle();if(!l)throw fail(404,"Payment link not found.");if(l.status!=="active"||new Date(l.expires_at)<new Date())throw fail(410,"Payment link has expired.");return json(res,200,{success:true,link:{title:l.title,description:l.description,amount:l.amount,status:l.status,expires_at:l.expires_at}});}
if(method==="POST"&&p.match(/^\/api\/v1\/public\/links\/[^/]+\/pay$/)){const slug=decodeURIComponent(p.split("/")[5]);const {data:l}=await db().from("payment_links").select("*").eq("slug",slug).maybeSingle();if(!l)throw fail(404,"Payment link not found.");const result=await startPayment(l);return json(res,201,{success:true,order:result});}
if(method==="GET"&&p.startsWith("/api/v1/public/payments/")){const orderId=decodeURIComponent(p.split("/").pop()),slug=url.searchParams.get("link");if(!slug)throw fail(400,"Payment link reference is required.");const {data:l}=await db().from("payment_links").select("id").eq("slug",slug).maybeSingle();if(!l)throw fail(404,"Payment link not found.");const o=await verifyOrder(orderId,l.id);return json(res,200,{success:true,order:{id:o.provider_order_id,status:o.status,amount:o.amount,upiId:o.upi_id}});}
if(method==="GET"&&p==="/api/v1/transactions"){const u=await currentUser(req);const {data,error}=await db().from("payment_orders").select("id,provider_order_id,amount,status,created_at,platform_fee").eq("user_id",u.id).order("created_at",{ascending:false}).limit(200);if(error)throw fail(500,"Could not load transactions.");return json(res,200,{transactions:data||[]});}
if(method==="GET"&&p.startsWith("/api/v1/payments/")){const u=await currentUser(req),oid=decodeURIComponent(p.split("/").pop());const {data:o}=await db().from("payment_orders").select("*").eq("provider_order_id",oid).eq("user_id",u.id).maybeSingle();if(!o)throw fail(404,"Payment not found.");const updated=await verifyOrder(oid,o.link_id);return json(res,200,{success:true,order:{id:updated.provider_order_id,status:updated.status,amount:updated.amount}});}
if(method==="POST"&&p==="/api/v1/api-keys"){const u=await auth(req);const raw="px_live_"+crypto.randomBytes(28).toString("hex");const {error}=await db().from("api_keys").insert({id:id(),user_id:u.id,key_hash:sha(raw),label:"Default API key",created_at:now()});if(error)throw fail(500,"Could not create API key.");return json(res,201,{success:true,key:raw});}
if(method==="GET"&&p==="/api/v1/subscriptions/plans"){const {data,error}=await db().from("plans").select("id,name,price,validity_days,link_limit,api_access,active").eq("active",true).order("price");if(error)throw fail(500,"Could not load plans.");return json(res,200,{plans:(data||[]).map(x=>({...x,validity_label:x.validity_days===1?"day":x.validity_days===7?"week":x.validity_days===30?"month":`${x.validity_days} days`}))});}
if(method==="POST"&&p==="/api/v1/subscriptions/subscribe"){const u=await auth(req);const {data:plan}=await db().from("plans").select("*").eq("id",b.planId).eq("active",true).maybeSingle();if(!plan)throw fail(404,"Plan not found.");const link=await makeLink(u,{amount:plan.price,title:`Subscription: ${plan.name}`,description:`PayX ${plan.name} plan`,expiryMinutes:Number(process.env.DEFAULT_LINK_EXPIRY_MINUTES||10)},{subscriptionPlanId:plan.id});return json(res,201,{success:true,link});}
if(method==="GET"&&p==="/api/v1/admin/dashboard"){await auth(req,true);const {data:users}=await db().from("users").select("id",{count:"exact"});const {data:links}=await db().from("payment_links").select("id",{count:"exact"});const {data:orders}=await db().from("payment_orders").select("provider_order_id,user_id,amount,status,created_at").order("created_at",{ascending:false}).limit(500);const arr=orders||[],success=arr.filter(x=>x.status==="success"),today=new Date().toISOString().slice(0,10),month=new Date().toISOString().slice(0,7);const volume=a=>a.reduce((s,x)=>s+Number(x.amount),0);const userIds=[...new Set(arr.map(x=>x.user_id))];const {data:us}=userIds.length?await db().from("users").select("id,email").in("id",userIds):{data:[]};const map=Object.fromEntries((us||[]).map(x=>[x.id,x.email]));return json(res,200,{users:users?.length||0,links:links?.length||0,transactions:arr.length,volume:volume(success),today:volume(success.filter(x=>x.created_at?.startsWith(today))),month:volume(success.filter(x=>x.created_at?.startsWith(month))),recent:arr.slice(0,10).map(x=>({...x,email:map[x.user_id]}))});}
if(method==="GET"&&p==="/api/v1/admin/users"){await auth(req,true);const {data,error}=await db().from("users").select("id,email,mobile,full_name,role,status,created_at").order("created_at",{ascending:false}).limit(500);if(error)throw fail(500,"Could not load users.");return json(res,200,{users:data||[]});}
if(method==="PATCH"&&p.startsWith("/api/v1/admin/users/")){const admin=await auth(req,true),uid=p.split("/").pop(),status=b.status;if(!["active","suspended"].includes(status))throw fail(400,"Invalid account status.");if(uid===admin.id&&status==="suspended")throw fail(400,"Cannot suspend your own admin account.");const {error}=await db().from("users").update({status}).eq("id",uid).neq("role","admin");if(error)throw fail(500,"User update failed.");await audit(admin.id,"user_status_changed",{target_user_id:uid,status});return json(res,200,{success:true});}
if(method==="GET"&&p==="/api/v1/admin/transactions"){await auth(req,true);const {data,error}=await db().from("payment_orders").select("id,provider_order_id,user_id,amount,status,created_at").order("created_at",{ascending:false}).limit(500);if(error)throw fail(500,"Could not load transactions.");const ids=[...new Set((data||[]).map(x=>x.user_id))];const {data:us}=ids.length?await db().from("users").select("id,email").in("id",ids):{data:[]};const m=Object.fromEntries((us||[]).map(x=>[x.id,x.email]));return json(res,200,{transactions:(data||[]).map(x=>({...x,email:m[x.user_id]}))});}
if(method==="GET"&&p==="/api/v1/admin/plans"){await auth(req,true);const {data,error}=await db().from("plans").select("*").order("created_at",{ascending:false});if(error)throw fail(500,"Could not load plans.");return json(res,200,{plans:data||[]});}
if(method==="POST"&&p==="/api/v1/admin/plans"){const a=await auth(req,true);const name=String(b.name||"").trim(),price=cleanAmount(b.price),days=Number(b.validityDays),limit=Number(b.linkLimit);if(!name||price<1||!Number.isInteger(days)||days<1||!Number.isInteger(limit)||limit<1)throw fail(400,"Provide plan name, price, validity and link limit.");const {data,error}=await db().from("plans").insert({id:id(),name,price,validity_days:days,link_limit:limit,api_access:!!b.apiAccess,active:true,created_at:now()}).select("*").single();if(error)throw fail(500,"Plan creation failed.");await audit(a.id,"plan_created",{plan_id:data.id});return json(res,201,{success:true,plan:data});}
throw fail(404,"PayX API route not found.");
}catch(e){return json(res,e.status||500,{success:false,error:e.message||"Internal server error."});}}
export default async function(req,res){try{return await handler(req,res)}catch(e){return json(res,500,{success:false,error:"Internal server error."})}}
